package photo_renamer;

public class ImageNotFoundException extends Exception{

	/**
	 * This exception is thrown when an image is not found in a directory
	 * 
	 * serialVersionUID: generated by eclipse so this class can be serialized.
	 */
	private static final long serialVersionUID = -8278440395107600494L;
	ImageNotFoundException(){
		super("There is no such image in the directory");
		super.printStackTrace();
	}

}
