package photo_renamer;

public class TagNotFoundException extends Exception{

	/**
	 * This exception is thrown when a tag is not found in an image
	 * 
	 * serialVersionUID: generated by eclipse so this class can be serialized.
	 */
	private static final long serialVersionUID = 7877421396067414316L;
	TagNotFoundException(){
		super("This image does not contain the given tag");
		super.printStackTrace();
	}

}
